name = "Yorha Cobbles Together"
author = "LTN_Akagi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "509df056b157ccbb225862e003115eced5ff7184974796264521c4fb8f955926"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
