name = "Yorha Cobbles Together"
author = "LTN_Akagi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "af8aa52b049405a1a08622ca25389a82c7ec3805bd4b2972d13cbe7531187fc7"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
