name = "Yorha Cobbles Together"
author = "LTN_Akagi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2858a83c65f567ff4a8de45af21e14341dda379ba923bf5bab0c6582865075eb"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
