name = "Yorha Cobbles Together"
author = "LTN_Akagi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "78a174293ecef4a5276dc09632c9bfb0e803339c61af7f78cc685b56d1e86c5a"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
