name = "Yorha Cobbles Together"
author = "LTN_Akagi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a898914ed1bd110aab97d4a91de6ec9a25d3f13e3a2f5de8ceaaf9eae0711ce8"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
