name = "Yorha Cobbles Together"
author = "LTN_Akagi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "fb2bfda6600cee2f9f351571127d31ccc0bf8e685835cd0ec8cec6f48351b9df"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
