name = "Yorha Cobbles Together"
author = "LTN_Akagi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d33c337e27e4765deea529b5c340df8bf4b4014aea0bbc41e4cf2bf21f062d1a"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
