name = "Yorha Cobbles Together"
author = "LTN_Akagi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8eeab00afa331b81aeab68dcf679bc6e2f25a732c6debbc8e7c2c0d03871abfe"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
