name = "Yorha Cobbles Together"
author = "LTN_Akagi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d34155d24e95a9210135c2f03346e1ccb6bb06d2ac305220ce48d9375e8ff8f1"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
