name = "Yorha Cobbles Together"
author = "LTN_Akagi"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "50288d591ef2503d861cd4698a1e6ff72a7a49170a69b301a3e7d0357730693d"

[versions]
forge = "47.3.1"
minecraft = "1.20.1"
